# Generated by Django 4.0.4 on 2022-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_name_product_price_product_reduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garantie',
            field=models.IntegerField(default=0),
        ),
    ]
