# Generated by Django 4.0.4 on 2022-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
