# Generated by Django 4.0.4 on 2022-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_contactus_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='fullname',
            field=models.TextField(max_length=50),
        ),
    ]
