# Generated by Django 4.0.4 on 2022-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_contactus_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
